### ISSUE TITLE
ELF解析错误

### ISSUE THREAD

**Issue by vapour** [DavidCai1993/lock.js#11]
当执行node app.o时遇到以下错误
`(function (exports, require, module, __filename, __dirname) { ELF
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3`

**Comment by DavidCai1993** [comment]
别执行 `node app.o` ，直接执行可执行文件： `./app.o`
